import {addTranslation} from '../../translate/Translate';
interface Translation {
    [language: string]: {
      [key: string]: string;
    };
  }
  
const translations: Translation = {
    tr: {
        solutions: "Çözümler",
        company: "Şirket",
        resources: "Kaynaklar",
        byIndustry: "Sektörel Çözüm",
        bySolutions: "Proje Çözümleri",
        health: "Sağlık",
        manufacturing: "Üretim",
        agriculture: "Tarım",
        car: "Kapalı Alan Araç Takibi ve Plaka Tanıma Sistemleri",
        port: "Liman Operasyonları",
        team: "Takımımız",
        partners: "Ortaklar",
        case_study: "Vaka Çalışmaları",
        webinars: "Web Seminerleri",
        news: "Haberler",
        tech_stack: "Teknoloji altyapısı",
        projects: "Projelerimiz",
        ethical_values: "Etik Değerler",
        core: "Bilgisayarlı Görü Türleri",
        blog: "Blog",
        brochure: "Broşür",
        contactUs: "Bize ulaş",
        language: "Dil Seç",
        fullNameRequired: "Tam isim gereklidir",
        emailRequired: "E-mail gereklidir",
        messageRequired: "Mesaj gereklidir",
        topicRequired: "Mesaj konusu gerklidir",
        validNumber: "Numarayı doğru yazınız",
        validEmail: "Email'i doğru yazınız",
        modalTitle: "Size yardımcı olmak için buradayız.",
        modalText: "İlginize çok değer veriyoruz. Lütfen formu doldurmak için bir dakikanızı ayırın; ekibimiz sorunuza en kısa sürede yanıt verecektir.",
        callText: "Ara",
        fullName: "Ad Soyad",
        phoneNumber: "Telefon Numarası",
        messageTopic: "Mesaj Konusu",
        selectTopic: "Mesak konusunu seçin",
        topic1: "Demo Talebi",
        topic2: "Teklif Al",
        topic3: "Genel Sorular",
        message: "Mesaj",
        submit: "Onay"
    },
    en: {
        solutions: "Solutions",
        company: "Company",
        resources: "Resources",
        byIndustry: "By Industry",
        bySolutions: "By Solutions",
        health: "Health",
        manufacturing: "Manufacturing",
        agriculture: "Agriculture",
        car: "Indoor Car Tracking & License Plate Detection",
        port: "Port Operations",
        team: "Team",
        partners: "Partners",
        case_study: "Case Studies",
        webinars: "Webinars",
        news: "News",
        tech_stack: "Tech Stack",
        projects: "Projects",
        ethical_values: "Ethical Values",
        core: "Core",
        blog: "Blog",
        brochure: "Brochure",
        contactUs: "Contact Us",
        language: "Language",
        fullNameRequired: "Full name is required",
        emailRequired: "E-mail is required",
        messageRequired: "Message is required",
        topicRequired: "Topic is required",
        validNumber: "Phone number is not valid",
        validEmail: "Invalid email address",
        modalTitle: "We are here to assist you.",
        modalText: "We highly value your interest. Please take a moment to complete the form and our team will respond promptly to your inquiry.",
        callText: "Call",
        fullName: "Full Name",
        phoneNumber: "Phone Number",
        messageTopic: "Message Topic",
        selectTopic: "Select a topic",
        topic1: "Demo Request",
        topic2: "Get an Offer",
        topic3: "General Questions",
        message: "Message",
        submit: "Submit"
    }
};

addTranslation(translations);