import {addTranslation} from '../../translate/Translate';

addTranslation({
    tr: {
        solutions: "Çözümler",
        company: "Şirket",
        resources: "Kaynaklar",
        byIndustry: "Sektörel Çözüm",
        bySolutions: "Proje Çözümleri",
        health: "Sağlık",
        manufacturing: "Üretim",
        agriculture: "Tarım",
        car: "Kapalı Alan Araç Takibi ve Plaka Tanıma Sistemleri",
        port: "Liman Operasyonları",
        team: "Takımımız",
        partners: "Ortaklar",
        case_study: "Vaka Çalışmaları",
        webinars: "Web Seminerleri",
        news: "Haberler",
        tech_stack: "Teknoloji altyapısı",
        projects: "Projelerimiz",
        ethical_values: "Etik Değerler",
        core: "Bilgisayarlı Görü Türleri",
        blog: "Blog",
        brochure: "Broşür",
        language: "Dil Seç"
    },
    en: {
        solutions: "Solutions",
        company: "Company",
        resources: "Resources",
        byIndustry: "By Industry",
        bySolutions: "By Solutions",
        health: "Health",
        manufacturing: "Manufacturing",
        agriculture: "Agriculture",
        car: "Indoor Car Tracking & License Plate Detection",
        port: "Port Operations",
        team: "Team",
        partners: "Partners",
        case_study: "Case Studies",
        webinars: "Webinars",
        news: "News",
        tech_stack: "Tech Stack",
        projects: "Projects",
        ethical_values: "Ethical Values",
        core: "Core",
        blog: "Blog",
        brochure: "Brochure",
        language: "Language"
    }
});